data = [
    {
        'name': 'instagram',
        'follower_count': 346,
        'description': 'social media platform',
        'country': 'United States',
    },
    {
        'name': 'Cristiano Ronaldo',
        'follower_count': 215,
        'description': 'Footballer',
        'country': 'Portugal',
    },
    {
        'name': 'Kim Kardashian',
        'follower_count': 215,
        'description': 'TV personality',
        'country': 'United States',
    },
    {
        'name': 'Selena Gomez',
        'follower_count': 230,
        'description': 'Singer and Actress',
        'country': 'United States',
    },
    {
        'name': 'Lionel Messi',
        'follower_count': 180,
        'description': 'Footballer',
        'country': 'Argentina',
    },
    {
        'name': 'Beyoncé',
        'follower_count': 155,
        'description': 'Singer and Actress',
        'country': 'United States',
    },
    {
        'name': 'Neymar Jr.',
        'follower_count': 156,
        'description': 'Footballer',
        'country': 'Brazil',
    },
    {
        'name': 'Kylie Jenner',
        'follower_count': 250,
        'description': 'TV personality',
        'country': 'United States',
    },
    {
        'name': 'Dwayne Johnson',
        'follower_count': 160,
        'description': 'Actor and Wrestler',
        'country': 'United States',
    },
    {
        'name': 'Taylor Swift',
        'follower_count': 145,
        'description': 'Singer and Songwriter',
        'country': 'United States',
    },
    {
        'name': 'LeBron James',
        'follower_count': 90,
        'description': 'NBA Player',
        'country': 'United States',
    },
    {
        'name': 'Kendall Jenner',
        'follower_count': 135,
        'description': 'Model',
        'country': 'United States',
    },
    {
        'name': 'Virat Kohli',
        'follower_count': 110,
        'description': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Ellen DeGeneres',
        'follower_count': 80,
        'description': 'TV Host and Comedian',
        'country': 'United States',
    },
    {
        'name': 'Shakira',
        'follower_count': 130,
        'description': 'Singer and Dancer',
        'country': 'Colombia',
    },
    {
        'name': 'Lionel Messi',
        'follower_count': 160,
        'description': 'Footballer',
        'country': 'Argentina',
    },
    {
        'name': 'Ariana Grande',
        'follower_count': 190,
        'description': 'Singer',
        'country': 'United States',
    },
    {
        'name': 'Roger Federer',
        'follower_count': 75,
        'description': 'Tennis Player',
        'country': 'Switzerland',
    },
    {
        'name': 'Narendra Modi',
        'follower_count': 60,
        'description': 'Prime Minister of India',
        'country': 'India',
    },
    {
        'name': 'Oprah Winfrey',
        'follower_count': 95,
        'description': 'TV Host and Philanthropist',
        'country': 'United States',
    },
    {
        'name': 'Miley Cyrus',
        'follower_count': 120,
        'description': 'Singer and Actress',
        'country': 'United States',
    },
    {
        'name': 'Usain Bolt',
        'follower_count': 70,
        'description': 'Sprinter',
        'country': 'Jamaica',
    }
]